# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  uglifyjs = nodeEnv.buildNodePackage {
    name = "uglifyjs";
    packageName = "uglifyjs";
    version = "2.4.11";
    src = fetchurl {
      url = "https://registry.npmjs.org/uglifyjs/-/uglifyjs-2.4.11.tgz";
      sha1 = "3440d64e045759589524418eb641c68bb90d113e";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Use 'uglify-js' instead - https://github.com/mishoo/UglifyJS2";
    };
    production = true;
    bypassCache = true;
  };
}