name:                grbr
version:             0.1.0.0
github:              "jhrcek/grbr"
license:             BSD3
author:              "Jan Hrček"
maintainer:          "example@example.com"
copyright:           "2019 Jan Hrček"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/jhrcek/grbr#readme>

dependencies:
- base >= 4.7 && < 5
- fgl
- text

ghc-options:
- -Wall

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - graphviz
    - optparse-applicative

executables:
  grbr:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grbr
    - scotty
    - open-browser
    - file-embed
    - bytestring

tests:
  grbr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grbr
